/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Freemodels (https://sketchfab.com/vivaanarora9)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-c9ba17582be94c6f8b610eede5f060cf
title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Earth({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={3}>
            <group rotation={[-0.53, 1.13, 0.12]}>
              <mesh geometry={nodes.Object_4.geometry} material={materials.Earth_Diffuse_6K} />
            </group>
            <group rotation={[-0.53, 1.13, 0.12]}>
              <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth.gltf')
