/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ARCTIC  WOLVES™ (https://sketchfab.com/arctic.wolves)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mars-156a95dfec244e07a3ae423f579ffb05
title: Mars
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/myMars.gltf')
  useFrame(({clock}) =>{
    const elapsedTime = clock.getElapsedTime();
    group.current.rotation.y = elapsedTime/6;
  
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.95} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, -2.5, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Mars_LOD0_MarsLOD1_0.geometry} material={materials.MarsLOD1} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/myMars.gltf')
